export enum ServiceEventType {
  CHANNEL_RAW_DATA_UPDATED = "CHANNEL_RAW_DATA_UPDATED",
  TEAM_REPO_INITIATED = "TEAM_REPO_INITIATED",
  CHANNEL_REPO_INITIATED = "CHANNEL_REPO_INITIATED",
  CHANNEL_REPOS_INITIATED = "CHANNEL_REPOS_INITIATED",
  CHANNEL_REPO_ALREADY_UPDATING = "CHANNEL_ALREADY_UPDATING",
}
