service: scalable-brain-refine
frameworkVersion: "2"
variablesResolutionMode: "20210326"
configValidationMode: error
useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-monorepo
custom:
  esbuild:
    loader:
      .graphql: text
  project_name: scalable-brain
  service_name: refine
  service_parameter_prefix: ${self:custom.project_name}/${opt:stage}/${self:custom.service_name}
  shared_parameter_prefix: ${self:custom.project_name}/prod/shared
  event_bus: ${ssm:/${self:custom.shared_parameter_prefix}/event_bus}
  auth_lookup_table: ${ssm:/${self:custom.shared_parameter_prefix}/tables/auth_lookup}
  knowledge_base_bucket: ${ssm:/${self:custom.service_parameter_prefix}/buckets/knowledge_base}
  function_prefix: ${self:custom.project_name}-${self:custom.service_name}-${opt:stage}
  init_team: ${self:custom.function_prefix}-init-team
  function_role: ${ssm:/${self:custom.service_parameter_prefix}/roles/function}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  iam:
    role: ${self:custom.function_role}
  region: eu-west-1

functions:
  initTeam:
    handler: src/index.initTeam
    events:
      - eventBridge:
          eventBus: ${self:custom.event_bus}
          pattern:
            detail-type:
              - TEAM_AUTHENTICATED
    environment:
      KNOWLEDGE_BASE_BUCKET: ${self:custom.knowledge_base_bucket}
      AUTH_LOOKUP_TABLE: ${self:custom.auth_lookup_table}
      HANDLER_NAME: ${self:custom.init_team}
      EVENT_BUS_NAME: ${self:custom.event_bus}
