app: scalable-brain
service: mine
frameworkVersion: "2"
variablesResolutionMode: "20210326"
configValidationMode: error
useDotenv: true
plugins:
  - serverless-plugin-monorepo
custom:
  service_parameter_prefix: scalable-brain/${opt:stage}/mine
  shared_parameter_prefix: scalable-brain/prod/shared
  datalake_bucket: ${ssm:/${self:custom.shared_parameter_prefix}/buckets/datalake}
  auth_lookup_table: ${ssm:/${self:custom.service_parameter_prefix}/tables/auth_lookup}
  event_bus: ${ssm:/${self:custom.shared_parameter_prefix}/event_bus}
  function_prefix: lefthoek-prototype-upstream-${opt:stage}
  oauth: ${self:custom.function_prefix}-oauth
  init_team: ${self:custom.function_prefix}-init-team
  init_channels: ${self:custom.function_prefix}-init-channels
  mine_channel: ${self:custom.function_prefix}-mine-channel
  function_role: ${ssm:/${self:custom.service_parameter_prefix}/roles/function}
  slack_credentials: ${ssm:/${self:custom.service_parameter_prefix}/credentials/slack}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  iam:
    role: ${self:custom.function_role}
  region: eu-west-1

functions:
  oauth:
    handler: dist/index.slack
    events:
      - httpApi:
          path: /integrations/slack
          method: get
    environment:
      SLACK_CREDENTIALS: ${self:custom.slack_credentials}
      SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
      AUTH_LOOKUP_TABLE: ${self:custom.auth_lookup_table}
      EVENT_BUS_NAME: ${self:custom.event_bus}
      HANDLER_NAME: ${self:custom.oauth}
