service: scalable-brain-mine
frameworkVersion: "2"
variablesResolutionMode: "20210326"
configValidationMode: error
useDotenv: true
plugins:
  - serverless-plugin-monorepo
custom:
  service_parameter_prefix: scalable-brain/${opt:stage}/mine
  shared_parameter_prefix: scalable-brain/prod/shared
  event_bus: ${ssm:/${self:custom.shared_parameter_prefix}/event_bus}
  raw_data_bucket: ${ssm:/${self:custom.service_parameter_prefix}/buckets/raw_data}
  auth_lookup_table: ${ssm:/${self:custom.service_parameter_prefix}/tables/auth_lookup}
  slack_client_id: ${ssm:/${self:custom.service_parameter_prefix}/credentials/slack/client_id}
  slack_client_secret: ${ssm:/${self:custom.service_parameter_prefix}/credentials/slack/client_secret}
  slack_signing_secret: ${ssm:/${self:custom.service_parameter_prefix}/credentials/slack/signing_secret}
  function_prefix: lefthoek-prototype-upstream-${opt:stage}
  oauth: ${self:custom.function_prefix}-oauth
  init_team: ${self:custom.function_prefix}-init-team
  init_channels: ${self:custom.function_prefix}-init-channels
  mine_channel: ${self:custom.function_prefix}-mine-channel
  function_role: ${ssm:/${self:custom.service_parameter_prefix}/roles/function}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  iam:
    role: ${self:custom.function_role}
  region: eu-west-1

functions:
  oauth:
    handler: dist/index.echo
