service: scalable-brain-api
frameworkVersion: "2"
variablesResolutionMode: "20210326"
configValidationMode: error
useDotenv: true
plugins:
  - serverless-plugin-monorepo
custom:
  project_name: scalable-brain
  service_name: api
  function_prefix: ${self:custom.project_name}-${self:custom.service_name}-${opt:stage}
  graphql: ${self:custom.function_prefix}-graphql

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  region: eu-west-1

functions:
  graphql:
    handler: dist/index.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphiql
          method: any
          cors: true
  subscriptions:
    handler: dist/index.graphql
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    environment:
      HANDLER_NAME: ${self:custom.graphql}
