name: landing
on:
  push:
    branches:
      - homepage
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Deploy Services"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "scalable-brain"
      BUILD_STAGE: "dev"
    steps:
      - uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/${{ env.PROJECT_NAME }}/${{ env.BUILD_STAGE }}/homepage/buckets/homepage"
          env_variable_name: "LANDING_BUCKET"
      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/${{ env.PROJECT_NAME }}/${{ env.BUILD_STAGE }}/homepage/distribution/id"
          env_variable_name: "LANDING_DISTRIBUTION_ID"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: yarn install
      - name: Build Dependencies
        run: echo 'yarn build'
      - name: Build Site
        run: yarn workspace @lefthoek/dashboard build
      - name: Deploy Site
        uses: reggionick/s3-deploy@v3
        with:
          folder: sites/dashboard/build
          bucket: ${{ env.LANDING_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          dist-id: ${{ env.LANDING_DISTRIBUTION_ID }}
