on:
  push:
    branches:
      - infra
      - main
      - stable
  pull_request:

jobs:
  infra:
    name: "Deploy Infra"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          TF_WORKSPACE: |
            stable:prod
            main:dev
            infra:dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        if: github.ref == 'refs/heads/infra' && github.event_name == 'push'
        run: terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
      - name: Terraform Apply
        if: github.ref == 'refs/heads/stable' && github.event_name == 'push'
        run: terraform apply -auto-approvee
