on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  infra:
    name: "Deploy Infra"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          TF_WORKSPACE: |
            !tag:prod
            !default:dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.ref != 'refs/head/main'
        run: terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
      - name: Terraform Apply
        if: startsWith(github.ref, 'refs/tags/releases/')
        run: terraform apply -auto-approve
