name: "deploy all"

on:
  push:
    branches:
      - main

jobs:
  services:
    name: "Deploy Services"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: iamtheyammer/branch-env-vars@v1.0.3
        with:
          SLS_ENVIRONMENT: |
            stable:prod
            main:dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: yarn install
      - name: Use Husky
        run: yarn prepare
      - name: Build Packages Code
        run: yarn build:packages
      - name: Build Services code
        run: yarn build:services
      - name: Deploy Services Code
        run: yarn deploy:services
